---
kafka:
  compression-codec: zstd
metadata:
  workers: 10
  provider:
    type: snmp
    communities:
      ::/0: public
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 6
      receive-buffer: 10485760
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760
core:
  workers: 6
  override-sampling-rate: 256
  exporter-classifiers: !include "exporter-classifiers.yaml"
  interface-classifiers: !include "interface-classifiers.yaml"

